### ISSUE TITLE
标注、笔记整理系统

### ISSUE THREAD

**Issue by scottming** [scottming/OMOOC2py#1]
# 项目名称：笔记整理系统
## 发起人的优势：

@scottming，风险投资公司投资经理一枚，每月看数百个项目，对需求的洞察能力比较强。之前也参加过「开智写作班」，具备一定认知科学基础，在用户体验上能做一些把控。同时有投资人资源，产品迭代到一定程度，可以直接对接。
@4plus-ma，大4广告学学生，爱折腾各种软件，懂设计、懂摄影，同时也是「开智写作班」一期学员，可以负责出想法、设计 UI、做 Keynote、项目路演等。
#### 场景：

我们经常阅读电子书，并标注、写笔记等，但遇到比较多的问题就是，这些标注、笔记等导出非常麻烦，导致无法形成输出，现有的一些软件提供的解决办法，但还有很多优化的空间。
#### 解决思路：

利用 Python 程序实现自动导出。
#### 1.[clippings](https://www.clippings.io/) 、 [知乎介绍](https://www.zhihu.com/question/22356174/answer/21121444?group_id=139440893)
- 功能：
  - 支持导出到 Evernote、本地pdf、txt等形式
- 亮点：
  - 导出的 Evernote 文件比较易读。
  - 导出方式比较多。
- 缺陷：
  - 导出的本地文件阅读效果差。
  - 不够智能化。
  - 只有英文版。
#### 2.[kindlemate](http://pan.baidu.com/s/1i3Hocol#path=%252FKindleMate-%25E6%25A0%2587%25E6%25B3%25A8%25E7%25AC%2594%25E8%25AE%25B0%25E5%258F%258A%25E7%2594%259F%25E8%25AF%258D%25E6%259C%25AC%25E7%25AE%25A1%25E7%2590%2586%25E5%2599%25A8%2520For%2520Kindle)
- 功能：
  - 支持导出本地文件
- 亮点：
  - 可以自定义导出的一些文件
- 缺陷：
  - 导出的本地文件不好读。
  - 不够智能化。
#### 3.多看自带导出功能
- 功能：
  - 绑定印象笔记，导出。
    -亮点：
  - 无
- 缺陷：
  - 无法导出到本地
  - 不够智能
  - 导出到印象笔记的标注没有页数标明
## 现有的代码基础

@scottming,笨方法刷到36题；@4plus-ma，笨方法刷到21题。
## 未来发展策划,市场/用户/系统压力预测...

暂无
## 版本规划,第几周应该完成的功能点

8W 完成基本框架
9W 待定......

**Comment by penguinjing** [comment]
- 请问2位发起人的地理位置。

**Comment by scottming** [comment]
@penguinjing 厦门
